In [169]:
###I created this in google colab###
import numpy as np
import pandas as pd
import math
import random
!pip install dtaidistance
from dtaidistance import dtw
from dtaidistance import dtw_visualisation as dtwvis
#create all of our data points in a numpy array
p1 = np.array((1,2,4,5))
p2 = np.array((4,3,2,1))
p3 = np.array((1,1,1,0,0))
p4 = np.array((1,0,0,0,1))

Euclidean Distance

In [40]:
#calculte [p1.x-p2.x]**2 for every set that is in the arrays
array = zip(p1,p2) 
eudis1 = math.sqrt(sum([(p1_x - p2_x)**2 for p1_x, p2_x in array]))
print("Distance between p1 and p2")
print(eudis1)

array2 = zip(p2,p3)
eudis2 = math.sqrt(sum([(p2_x - p3_x)**2 for p2_x, p3_x in array2]))
print("Distance between p2 and p3")
print(eudis2)

Distance between p1 and p2
5.477225575051661
Distance between p2 and p3
3.872983346207417


Manhatten Distance

In [59]:
#First take the absolute value of all the datasets in the list, then sum them all 
array = zip(p1,p2)
mandis = sum(np.abs([(p1_x - p2_x) for p1_x, p2_x in array]))
print("Distance between p1 and p2")
print(mandis)

array2 = zip(p2,p3)
mandis2 = sum(np.abs([(p2_x - p3_x) for p2_x, p3_x in array2]))
print("Distance between p2 and p3")
print(mandis2)

Distance between p1 and p2
10
Distance between p2 and p3
7


Cosine Similarity

In [118]:
array = zip(p1,p2)

#x1= sum([(p1_x)**2 for p1_x in array])
#x2= sum([(p2_x)**2 for p2_x in array])
x1 = 1**2 * 2**2 * 4**2 * 5**2
x2 = 4**2 * 3**2 * 2**2 * 1**2
numerator=  sum([(p1_x - p2_x) for p1_x, p2_x in array])

denominator = math.sqrt(x1) * math.sqrt(x2)

print((numerator/denominator))




0.0020833333333333333


SMC Distance

In [160]:
#first we check every bit position to see if they match 
difference = 0
size = len(p1)
print(size)

for x in range(size):
  if p1[x] != p2[x]:
    difference += 1

print(difference)
print("Simple Matching Coeffecient")
print(difference/size)

4
4
Simple Matching Coeffecient
1.0


Jaccard Coeficient

In [135]:
p1 = np.array((1,2,4,5))
p2 = np.array((4,3,2,1))
p3 = np.array((1,1,1,0,0))
p4 = np.array((1,0,0,0,1))

#p1 and P2, first we will combine the sets. 
AuB = np.concatenate((p1, p2))
print(AuB)
#now we will find the simliar numbers in the array 
AnB = np.intersect1d(p1,p2)
print(AnB)

union = np.sum(AuB)
print(union)

same = np.sum(AnB)
print(same)

print("Jaccard Coefficient")
print((union-same)/union)

#p2 and P3, first we will combine the sets. 
AuB = np.concatenate((p2, p3))
print(AuB)
#now we will find the simliar numbers in the array 
AnB = np.intersect1d(p2,p3)
print(AnB)

union = np.sum(AuB)
print(union)

same = np.sum(AnB)
print(same)

print("Jaccard Coefficient")
print((union-same)/union)


[1 2 4 5 4 3 2 1]
[1 2 4]
22
7
Jaccard Coefficient
0.6818181818181818
[4 3 2 1 1 1 1 0 0]
[1]
13
1
Jaccard Coefficient
0.9230769230769231


Hamming distance

In [144]:
#first we check every bit position to see if they match 
value = 0
size = len(p3)
print(size)

for x in range(size):
  if p3[x] != p4[x]:
    value +=1 

print("hamming distance")
print(value)


5
hamming distance
3


DTW

In [168]:


distance = dtw.distance(p1, p3)
print(distance)
# plot
path = dtw.warping_path(p1, p3)
dtwvis.plot_warping(p1, p3, path, filename="warp.png")


6.48074069840786


(None, None)

Q2. Data preprocessing 

Grab 10 random Samples

In [182]:
url = 'https://raw.githubusercontent.com/anvalenz/CS488/main/BreastCancerCoimbra_imbalanced.csv'
df = pd.read_csv('https://raw.githubusercontent.com/anvalenz/CS488/main/BreastCancerCoimbra_imbalanced.csv')
print("Grab 10 random samples")
df.sample(n=10, random_state=1)


Grab 10 random samples


Age        BMI  Glucose  ...  Resistin     MCP.1  Classification
62   49  21.367521       78  ...  22.94254   737.672               2
27   66  31.446541       90  ...  23.38190  1102.110               1
53   45  20.829995       74  ...  28.03230   382.955               2
21   34  31.975015       87  ...   5.62592   572.783               1
26   50  38.578759      106  ...  11.78388   887.160               1
35   67  29.606767       79  ...   4.20750   585.307               1
2    82  23.124670       91  ...   9.27715   554.697               1
43   69  32.500000       93  ...  11.78796   270.142               1
49   85  26.600000       96  ...   9.61350   232.006               1
31   53  36.790166      101  ...  10.26309   695.754               1

[10 rows x 10 columns]

Grab 10 stratified samples


In [201]:
url = 'https://raw.githubusercontent.com/anvalenz/CS488/main/BreastCancerCoimbra_imbalanced.csv'
df = pd.read_csv('https://raw.githubusercontent.com/anvalenz/CS488/main/BreastCancerCoimbra_imbalanced.csv')
df.groupby('Age', group_keys=False).apply(lambda x: x.sample(min(len(x), 10)))


Age        BMI  Glucose  ...  Resistin     MCP.1  Classification
13   24  18.670000       88  ...   6.85000   632.220               1
12   25  22.860000       82  ...   5.14000   313.730               1
32   28  35.855815       87  ...  21.44366   358.624               1
11   29  23.010000       82  ...   4.58000   174.800               1
22   29  32.270788       84  ...  24.60330   904.981               1
..  ...        ...      ...  ...       ...       ...             ...
2    82  23.124670       91  ...   9.27715   554.697               1
1    83  20.690495       92  ...   4.06405   468.786               1
49   85  26.600000       96  ...   9.61350   232.006               1
4    86  21.111111       92  ...  10.57635   773.920               1
6    89  22.700000       77  ...  12.93610  1256.083               1

[67 rows x 10 columns]